# Generated by Django 2.1.2 on 2019-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetID', models.CharField(max_length=60)),
                ('assetType', models.CharField(choices=[('COMMON', 'Common stock'), ('PREFERRED', 'Prefered stock')], default='1', max_length=20)),
                ('purchaseDate', models.DateTimeField()),
                ('purchasePrice', models.FloatField()),
                ('volume', models.IntegerField()),
                ('saleDate', models.DateField()),
                ('salePrice', models.FloatField()),
                ('priceFeedType', models.CharField(choices=[('COMMON', 'Common stock'), ('PREFERRED', 'Prefered stock')], default='1', max_length=40)),
                ('priceFeedRef', models.CharField(max_length=20)),
                ('debtFeedType', models.CharField(max_length=20)),
                ('debtFeedRef', models.CharField(max_length=20)),
                ('percentOwnership', models.FloatField()),
                ('thresholds', models.CharField(max_length=20)),
            ],
        ),
    ]
