# Generated by Django 2.1.2 on 2019-02-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchaseDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='saleDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
