# Generated by Django 2.1.2 on 2019-02-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipi', '0002_auto_20190223_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchaseDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='saleDate',
            field=models.DateField(),
        ),
    ]
