# Generated by Django 2.1.2 on 2019-02-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipi', '0003_auto_20190223_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='debtFeedRef',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='debtFeedType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='saleDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='salePrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='thresholds',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
