# Generated by Django 2.1.2 on 2019-01-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='type',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='todo',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
