# Generated by Django 2.1.2 on 2019-01-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190105_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='finishDate',
            new_name='upDate',
        ),
        migrations.AddField(
            model_name='todo',
            name='timeSpent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
