# Generated by Django 2.1.2 on 2019-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190105_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='timeSpent',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
